server:
  port: 9000

spring:
  application:
    name: spring-data-rest

  h2:
    console:
      enabled: true

  sql:
    init:
      platform: h2


  datasource:
    url: jdbc:h2:mem:testdb

  jpa:
    hibernate:
      ddl-auto: update